address: 0.0.0.0:7373
root: ROOT_IDENTITY

tls:
  #key: /var/local/kes-server.key
  #cert: /var/local/kes-server.cert
  key: /etc/letsencrypt/live/KES_HOSTNAME/privkey.pem
  cert: /etc/letsencrypt/live/KES_HOSTNAME/cert.pem

policy:    
  minio:
    paths:
    - /v1/key/create/minio-*
    - /v1/key/generate/minio-*
    - /v1/key/decrypt/minio-*
    identities:
    - APP_IDENTITY

cache:
  expiry:
    any: 5m0s
    unused: 20s

keys:
  vault:
    endpoint: https://vault:8200
    prefix: minio
    approle:
      id: APPROLE_ID
      secret: APPROLE_SECRET_ID
      retry: 15s
    status:
      ping: 10s
    tls:
      #ca: /var/local/vault-server.cert
      ca: /etc/letsencrypt/live/VAULT_HOSTNAME/cert.pem

log:
  error: on
  audit: on
